### ISSUE TITLE
Interacting with Marks Spreadsheet doesn't stop session timeout

### ISSUE THREAD

**Issue by gfbee** [MarkUsProject/Markus#2926] opened 2017-04-18 18:39 UTC
I'm reviewing a TA's mark entries right now, clicking the checkboxes to keep track. That interaction doesn't appear to be enough to stop the session timeout.
Is it documented somewhere what stops session timeout for each page?

**Comment by arkon** [comment] 2017-04-18 18:43
I believe that it requires an actual page navigation (i.e. something that will actually hit the server to update the session). I don't think the way that it's being handled right now is that elegant though. While having the popup to indicate that a session is about to expire is a decent stopgap, it'd probably be better to actually ping the server in the background to keep the session rolling as long as the user is doing something that isn't necessarily a page navigation (i.e. moving their mouse, clicking things, typing, etc.).

**Comment by adisandro** [comment] 2018-04-16 16:06
Duplicate of #3303.

**Comment by adisandro** [comment] 2018-10-16 12:52
This was mostly fixed by #3448

**Closed by adisandro** 2018-10-16 12:52 UTC
Labels: duplicate
