### ISSUE TITLE
HTML escape '<' for view sourcecode

### ISSUE THREAD

**Issue by hysw** [MarkUsProject/Markus#1908] opened 2014-11-27 09:09 UTC
Some '<' are displayed as html escape code(although '>' seems to be fine).
Example: map (\strs -> [(str, f str)|str&amp;lt;-strs])
Link type: https://markus.cdf.toronto.edu/csc...-2014-09/en/assignments/.../submissions/.../results/.../view_marks

**Comment by david-yz-liu** [comment] 2015-01-18 19:31
@paymog Related to annotation text.

**Comment by paymog** [comment] 2015-03-06 18:12
I don't fully understand what the problem is. How can I reproduce it?

**Comment by david-yz-liu** [comment] 2015-03-06 18:34
Hmmm I just tried to put in the string `map (\strs -> [(str, f str)|str<-strs])` as an annotation, and it seemed to work fine. 

But @paymog a related issue has always been rendering html tags properly. This currently doesn't interact with nicely with the ability to edit annotations.

1. Create a new annotation with the text "<strong>hi</strong>"
2. Hover over the annotation: "hi" appears bolded
3. Go edit the annotation, but don't actually change anything, and click on "Submit Edit".
4. Go back to the submission, and hover over the annotation again.

In the current production version of MarkUs, the annotation now appears as "<strong>hi</strong>", without the styling applied. You could check to see if this still happens in the latest master branch, and if so, fix it.

**Comment by paymog** [comment] 2015-03-07 19:38
On master this styling still applies after doing the steps you've outlined. However, underlines using <u></u> don't. I didn't know that one of the use cases was to put HTML formatting into annotation system, I wonder if MathJax plays nice with that.

**Comment by arkon** [comment] 2015-03-07 19:51
`u` tags aren't meant for underlining in HTML5. Using `i` and `b` tags for text styling is also deprecated.

**Comment by paymog** [comment] 2015-03-07 21:48
Oh, ok. How are graders supposed to entered styled text in an annotation then?

**Comment by david-yz-liu** [comment] 2015-03-08 14:26
@paymog the tags themselves aren't deprecated, it's just their use for styling purposes is (though markers may still choose to use them in that way). I'm fine closing this issue then.

**Closed by david-yz-liu** 2015-03-08 14:26 UTC
