### ISSUE TITLE
Production bug: can't view results/annotations on submission

### ISSUE THREAD

**Issue by oneohtrix** [MarkUsProject/Markus#2009] opened 2015-01-20 16:16 UTC
![screen shot 2015-01-20 at 11 13 20 am](https://cloud.githubusercontent.com/assets/963922/5820833/b50ec992-a095-11e4-8a4d-efe712b71a20.png)
This is what I see. It looks like the asset link to pdfjs.worker.js is broken.

**Comment by david-yz-liu** [comment] 2015-01-20 16:23
Thanks for pointing this out, I'll fix it.

**Comment by arkon** [comment] 2015-01-20 16:25
Can confirm that this is happening (same CSC373 instance).

**Comment by david-yz-liu** [comment] 2015-01-20 16:27
Yeah, I know what the problem is. I fixed it a while ago for the TAs, but forgot about the students. My bad!

**Comment by david-yz-liu** [comment] 2015-01-20 18:57
@oneohtrix @arkon This problem should be fixed now (but let me know if it isn't).

**Closed** 2015-01-20 18:57 UTC

**Comment by arkon** [comment] 2015-01-20 19:29
@david-yz-liu Seems to be working now!
