### ISSUE TITLE
Markdown preview inconsistent with rendered text

### ISSUE THREAD

**Issue by AlexeyKhrabrov** [MarkUsProject/Markus#3433] opened 2018-07-05 21:10 UTC
See screenshots of input/preview and rendered result.

![preview](https://user-images.githubusercontent.com/9388553/42348099-20bf2d1c-8076-11e8-81b1-8689bcea2b4c.png)
![result](https://user-images.githubusercontent.com/9388553/42348103-2608f960-8076-11e8-9861-d8f5a614b2b4.png)

**Comment by mishaschwartz** [comment] 2018-07-06 13:22
This actually seems to be a more general issue that what is rendered in the preview panel is not what ends up in the final result. In fact, when looking at issue #3415 I noticed some inconsistencies between the preview of a new annotation and what gets displayed in the annotation tooltip text.  

Do you mind if I change the title of this issue to something like: "Markdown preview inconsistent with rendered text" and I'll look into the cause sometime in the future.

**Comment by david-yz-liu** [comment] 2019-10-12 02:23
This should be fixed now.

**Closed by david-yz-liu** 2019-10-12 02:23 UTC
Labels: bug
