### ISSUE TITLE
Adding annotation messes with mathematics

### ISSUE THREAD

**Issue by salehe** [MarkUsProject/Markus#3925] opened 2019-04-04 22:09 UTC
After adding annotations, some mathematic texts are transformed into non-sense. This seems to be some problem with fonts

Example:
![image](https://user-images.githubusercontent.com/1437198/55591872-bafae000-5704-11e9-9411-c284ba067060.png)

**Comment by mishaschwartz** [comment] 2019-04-05 13:06
Hi @salehe. Thanks for opening this issue.  

Can you please let me know what you typed into the annotations text box (the markdown/latex text) that generated the text you show, and what you expected the generated annotation text to look like? That will help us figure out the source of this bug.

**Comment by salehe** [comment] 2019-04-05 18:50
Hi @mishaschwartz,

The annotation looks fine. It's the original pdf text (before adding annotation) that is transformed.

**Comment by mishaschwartz** [comment] 2019-04-08 14:03
I believe I found the pdf that you referenced above but it is not rendered in the same way that your image shows. For me it looks like:

<img width="172" alt="Screen Shot 2019-04-08 at 9 59 33 AM" src="https://user-images.githubusercontent.com/4380924/55730032-516d2100-59e5-11e9-8f46-ba730099a992.png">

And it looks the same when I view it in Chrome, Firefox, Safari and also when I download it and view it through a few pdf viewers. How exactly are you viewing this file and are there any steps I am missing to reproduce this bug?

**Comment by mishaschwartz** [comment] 2019-06-21 12:44
Closing because unable to reproduce and no follow up

**Closed by mishaschwartz** 2019-06-21 12:44 UTC
