### ISSUE TITLE
Inconsistent UI state in automated testing page

### ISSUE THREAD

**Issue by dijkstracula** [MarkUsProject/Markus#4711] opened 2020-06-30 14:59 UTC
To reproduce: 

* Go to the "automated testing" page.  
* Check the "Enable tests for this assignment" checkbox.
* Create a new tester type.
* Navigate away from the automated testing page, clicking OK if your browser warns about state not being saved.
* Return to the automated testing page: the tester that we created above still appears, but "enable tests for this assignment" is unchecked.  

This presents a slightly confusing interface because the tester delete/add buttons are present but don't do anything, and don't indicate they're disabled visually.  It was only when I noticed that the checkbox was not set that I was able to do anything in the tester pane.

**Comment by mishaschwartz** [comment] 2020-07-02 13:40
Hi @dijkstracula, 

I am currently unable to reproduce this behaviour in either the master or production versions. When you say "Create a new tester type", do you mean just selecting one of the options from the dropdown menu or are there additional steps before you navigate away from the page?

Thanks

**Comment by dijkstracula** [comment] 2020-07-02 15:25
Hi @mishaschwartz ,

Yeah, I select "racket" and then click the test groups plus sign.

I recorded a video of what happens on my end; maybe that's clearer :) https://www.youtube.com/watch?v=-jpIRXLsIRs&feature=youtu.be

Nathan

**Comment by mishaschwartz** [comment] 2020-07-03 14:01
Thank you for that video! That makes everything easier!

That being said, what you've shown in the video is the intended behaviour as far as I can tell. Any changes you make to the page (including selecting the "Enable tests for this assignment" checkbox) are not saved when you navigate away from the page without saving. All buttons on the form are greyed out and not clickable unless the "Enable tests for this assignment" checkbox is selected. 

I'm also still not sure what you mean by "the tester that we created above still appears" since it appears to me from the video that the tester is no longer shown once you navigate back to the page after not saving.

**Comment by mishaschwartz** [comment] 2020-09-01 19:20
I'm going to close this because the behaviour shown in the video is the intended behaviour. Feel free to re-open if there are additional details that are missing.

**Closed by mishaschwartz** 2020-09-01 19:20 UTC
