### ISSUE TITLE
autograder saving output to submission repo yields "work was submitted after the deadline" warning

### ISSUE THREAD

**Issue by dijkstracula** [MarkUsProject/Markus#4737] opened 2020-07-11 18:33 UTC
I have an assignment that was due on 26 July right before midnight:

![image](https://user-images.githubusercontent.com/8949748/87231201-46d0d280-c372-11ea-864c-99e5b1705eea.png)

I've set up the autograder to drop a feedback file in their repo.  However, after the autograder runs, a box pops up indicating that the submission was submitted after the deadline.  However, this isn't the case, what was "submitted" after the deadline was the output file.

![image](https://user-images.githubusercontent.com/8949748/87231239-a29b5b80-c372-11ea-89a1-d79d94be1d4b.png)

**Comment by mishaschwartz** [comment] 2020-07-13 14:45
The proposed solution for this is #3697

**Comment by mishaschwartz** [comment] 2020-09-17 20:12
closing as duplicate of #3697

**Closed by mishaschwartz** 2020-09-17 20:12 UTC
