### ISSUE TITLE
Grades bars stretch indefinitely when hovered

### ISSUE THREAD

**Issue by tusooa** [MarkUsProject/Markus#5732] opened 2022-01-09 18:15 UTC
As title, on Firefox 95.0.1, GNU/Linux (X11)

https://user-images.githubusercontent.com/299873/148694916-7d67e1d8-829e-4044-b10b-a6609d55832f.mp4

**Comment by mishaschwartz** [comment] 2022-01-10 13:54
Duplicate of #5507

**Closed by mishaschwartz** 2022-01-10 13:54 UTC
