### ISSUE TITLE
Bug: inconsistent decimal when comma used as period

### ISSUE THREAD

**Issue by mishaschwartz** [MarkUsProject/Markus#2936] opened 2017-05-02 15:45 UTC
In the Manage Marks Spreadsheet view, when adding a mark to a cell, if a comma is used instead of period the cell total is counted as the digits up to the comma and no format error is raised (cell does not turn red)

![screen shot 2017-05-02 at 11 43 50](https://cloud.githubusercontent.com/assets/4380924/25626188/b34053d8-2f2c-11e7-9e65-9fdfe431f552.png)
![screen shot 2017-05-02 at 11 44 05](https://cloud.githubusercontent.com/assets/4380924/25626191/b6413822-2f2c-11e7-9f2d-8a8646a3f03e.png)

**Comment by adisandro** [comment] 2017-05-02 16:00
Duplicate of #2925

**Closed** 2017-12-10 19:49 UTC
