### ISSUE TITLE
markusproject.org is down

### ISSUE THREAD

**Issue by jeffling** [MarkUsProject/Markus#4246] opened 2019-11-22 00:26 UTC
Site doesn't seem to work

**Comment by mishaschwartz** [comment] 2019-11-22 14:15
duplicate of #3810

**Closed by mishaschwartz** 2019-11-22 14:15 UTC

**Comment by jeffling** [comment] 2019-11-22 22:40
https://github.com/MarkUsProject still in the org description

**Comment by mishaschwartz** [comment] 2019-11-25 18:35
Ah I see. Thanks for catching that! It has now been removed.
