### ISSUE TITLE
Rails 4 - scss warnings in server log

### ISSUE THREAD

**Issue by YusiFan** [MarkUsProject/Markus#1924] opened 2014-12-03 21:46 UTC
```
Warning. Error encountered while saving cache c0654524501a4d3513caee58728144b72b841d40/*.scssc: can't dump anonymous class #<Class:0x00000005c247a0>
```

This warnings appear when parsing scss, it seems like a bug in sprockets.
https://github.com/sass/sass/issues/1144
https://github.com/sass/sass/issues/1028

**Comment by tsimica** [comment] 2015-02-19 05:16
I'm not able to reproduce this issue. The first issue has a solution to update sass and sass-rails gems.  I've looked in Rails 4 Gemfile and the versions that are included are newer than what is mentioned in the issues linked. 

Consider closing? @david-yz-liu

**Comment by david-yz-liu** [comment] 2015-02-19 05:51
I just tried this out on the rails4 branch, and got the same error. sass and sprockets versions are what's in the Gemfile (newest, I presume). We can talk about this one more in person.

**Comment by tsimica** [comment] 2015-03-06 01:30
Issue was discussed in person. I'm using Ruby 2.1.3 (as opposed to Ruby 2.1.2) and not receiving any errors in the server console. Perhaps it has to do with this?

**Closed** 2015-06-26 16:42 UTC
