### ISSUE TITLE
Allow admin to be a grader

### ISSUE THREAD

**Issue by dijkstracula** [MarkUsProject/Markus#4710] opened 2020-06-30 14:35 UTC
I would like to help my TAs grade an assignment, but by default instructors (which is synonymous, I think with the admin user role?) aren't listed on the grader page.

![image](https://user-images.githubusercontent.com/8949748/86139069-87943600-baac-11ea-9958-967ce391e5e2.png)

When I attempt to add myself as a grader, I'm informed that I'm already part of the course.

![image](https://user-images.githubusercontent.com/8949748/86138980-67fd0d80-baac-11ea-8757-f0c6e3290dc6.png)

**Comment by mishaschwartz** [comment] 2020-07-02 13:44
admins/instructors (you're right they are synonymous) are able to grade any assignment. If you go to the "Submissions" tab for a given assignment, you should be able to select a group's submission to grade just like a grader would.

Please see here (and the sections below) for more details:

https://github.com/MarkUsProject/Markus/wiki/Instructor-Guide:-Marking-an-Assignment-(Grading-View)#prepare-to-grade

**Comment by dijkstracula** [comment] 2020-07-02 15:29
Hi Misha,

I'm able to grade assignments that have been assigned to TAs in an ad-hoc manner, but because I can't add myself to the list of graders, I can't be randomly assigned submissions to grade, AFAICT.

Nathan

**Comment by mishaschwartz** [comment] 2020-07-03 13:52
I understand, in that case I think this is a duplicate of #1221

**Closed by mishaschwartz** 2020-07-03 13:52 UTC
