### ISSUE TITLE
Marking Status selector changing back to unmarked when partial

### ISSUE THREAD

**Issue by mark-kazakevich** [MarkUsProject/Markus#1898] opened 2014-11-21 08:10 UTC
Regarding the marking status selector:
![screen shot 2014-11-21 at 3 08 30 am](https://cloud.githubusercontent.com/assets/4411302/5139405/b8e2a58c-712b-11e4-8767-ceab376ddb71.png)

When marking, it properly switches to 'partial'.  However, refreshing the page, or leaving it for another submission and coming back, causes it to go back to 'unmarked'. It makes sense for it to stay as 'partial'.

**Comment by tsimica** [comment] 2015-03-26 18:59
I looked into this issue. I'm not able to replicate the problem. I've tried it on both Firefox and Chrome (to make sure it wasn't a cashing issue). 

The Ajax request that triggers the setting of the marking status from unmarked to partial in the controller seems to be correct. I'm not too sure if this issue was fixed in a previous commit.

**Comment by david-yz-liu** [comment] 2015-03-26 19:44
Confirmed with @tsimica that this has been fixed.

**Closed by david-yz-liu** 2015-03-26 19:44 UTC
