### ISSUE TITLE
Error for Criteria/Grader csv download from graders view

### ISSUE THREAD

**Issue by melneubert** [MarkUsProject/Markus#2316] opened 2015-10-12 16:47 UTC
I noticed this error when trying to download a csv file from the graders view and selecting Criteria/Grader map CSV format. Seems to be coming from the download_grader_criteria_mapping function in graders_controller.

Backtrace:
  app/controllers/graders_controller.rb:143:in block in download_grader_criteria_mapping'
  app/controllers/graders_controller.rb:142:in download_grader_criteria_mapping'

ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "users"
LINE 1: ...iations".* FROM "criterion_ta_associations" WHERE "users"."t...
                                                             ^
: SELECT "criterion_ta_associations".* FROM "criterion_ta_associations" WHERE "users"."type" IN ('Ta') AND "criterion_ta_associations"."criterion_type" = 'RubricCriterion' AND "criterion_ta_associations"."criterion_id" IN (14, 13, 11, 12, 8, 9, 15, 10)):
  app/controllers/graders_controller.rb:143:in block in download_grader_criteria_mapping'
  app/controllers/graders_controller.rb:142:in download_grader_criteria_mapping'

**Comment by reidka** [comment] 2016-01-15 21:49
We can't reproduce this one. @melneubert do you remember anything else about when you encountered this bug?

**Comment by melneubert** [comment] 2016-01-16 04:10
Unfortunately I don't. Is it possible it could have been something related to my setup/database? (If so, sorry for reporting this)

**Comment by reidka** [comment] 2016-01-16 14:07
That's okay.  I just thought I would check.

We wil close this for now since we can't reproduce.

**Closed by reidka** 2016-01-16 14:07 UTC
