### ISSUE TITLE
Moving Annotations on JPGs

### ISSUE THREAD

**Issue by wkwan** [MarkUsProject/Markus#2307] opened 2015-10-04 04:23 UTC
If a JPG that already has an annotation is loaded with the cursor outside of the image area, and then the cursor is moved onto the image after it's loaded, the annotation will move.

Example:
Image loaded with cursor outside:
![screen shot 2015-10-04 at 12 22 41 am](https://cloud.githubusercontent.com/assets/2907892/10266409/1c06f50e-6a2e-11e5-8f40-f0d3c5c17674.png)
After moving cursor onto the image:
![screen shot 2015-10-04 at 12 23 01 am](https://cloud.githubusercontent.com/assets/2907892/10266410/1e62729c-6a2e-11e5-8629-3dccf84caefa.png)

The correct location of the annotation should be where it is in the second image.

**Comment by Sm1th** [comment] 2016-01-16 15:25
To add to this, 

* When scrolling and tab has focus, annotations do not move with the picture until you stop scrolling.
* When scrolling and tab _does not_ have focus, the annotations do not move until the tab has focus and the cursor is moved onto the image.

This happens with .jpg and .png files. Does not occur with .pdfs and plain text files.

**Comment by mishaschwartz** [comment] 2020-09-17 19:06
Reason for marking as invalid:

- can no longer reproduce issue
- Note: significant changes have been made to the annotation layer since this issue was raised

**Closed** 2020-09-21 20:26 UTC
Labels: invalid
