### ISSUE TITLE
grader assigned to one criteria can't delete an annotation from another criteria

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#5218] opened 2021-04-20 14:01 UTC
One of my TAs accidentally used an annotation from a different criteria for his question.  He then wasn't able to delete it.

Maybe graders should be able to delete annotations they used?

**Comment by david-yz-liu** [comment] 2024-09-18 00:43
Closing this issue, as we cannot reproduce it.

**Closed by david-yz-liu** 2024-09-18 00:43 UTC
Labels: bug
