### ISSUE TITLE
Grading interface attempts to render parts of a .tex file I'm grading, with undesirable results.

### ISSUE THREAD

**Issue by falsifian** [MarkUsProject/Markus#4435] opened 2020-03-12 15:38 UTC
Occasionally, I want to annotate a student's LaTeX source file. On one occasion, MarkUs tried to render the LaTeX in the file, but the result is much worse than if MarkUs simply left the file alone. MarkUs doesn't always try to do it; I'm not sure exactly what triggers it.

Here's a screenshot from the grading interface:

![image](https://user-images.githubusercontent.com/225893/76538224-e2127380-6476-11ea-92bb-86ffa3ed8c7d.png)

There are two problems here:

* Lots of "Undefined control sequence".
* Even when MarkUs does get it right, I can imagine in some situations I would want to comment on the source rather than the compiled version, e.g. to explain to the student why it rendered the wrong way.

(The situation I'm handling right now is that one student's compiled pdf is blank for some reason, so I'm grading their LaTeX source instead.)

**Comment by david-yz-liu** [comment] 2020-04-04 15:03
Thanks for reporting this! This should be fixed by #4278 (I was unable to reproduce this with a sample tex file on master), so it shouldn't be an issue in future terms.

**Closed by david-yz-liu** 2020-04-04 15:03 UTC
Labels: bug

**Comment by evank28** [comment] 2021-04-26 19:04
Are we sure this has been fixed? I've still seen this recently in Makefiles submitted to MarkUs. The below screenshot is a Makefile from the current CSC209 MarkUs instance running version 1.11.5.DEV.
![image](https://user-images.githubusercontent.com/34668740/116133323-93389500-a69c-11eb-9dee-fc3da1d03618.png).
I believe I've seen this in a .tex file in the CSC111 MarkUs instance too, but I couldn't find which one.
